sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
gemfile:
  - Gemfile
  - Gemfile-sprockets2-sprocketsrails2
  - Gemfile-sprockets3-sprocketsrails2
  - Gemfile-rails41
  - Gemfile-rails42
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
